[buildPlans.iosevka-clam]       # <iosevka-clam> is your plan name
family = "Iosevka Clam"         # Font menu family name
design = ['sp-fixed',
          'v-turn-v-straight',            # =
          'v-capital-g-toothless',        # =
          'v-capital-q-straight',         # =
          'v-capital-r-curly',            # =
          'v-capital-y-curly',            # =
          'v-a-doublestorey',             # = v-a-singlestorey
          'v-f-straight',                 # = v-f-tailed v-f-serifed
          'v-g-opendoublestorey',         # = v-g-doublestorey v-g-singlestorey
          'v-i-italic',                   # v-i-serifed
          'v-j-serifed',                  # v-j-line v-j-narrow
          'v-l-italic',                   # = v-l-hooky v-l-zshaped
          'v-k-curly',                    # ?
          'v-m-shortleg',                 # =, v-m-normal
#          'v-r-straight',                 # v-r-serifed, v-r-top-serifed
          'v-t-standard',                 # =, v-t-cross
          'v-u-with-bar',                 # =, v-u-without-bar
          'v-v-straight',                 # ?
          'v-w-curly',                    # =, v-w-straight
          'v-x-curly',                    # ?
          'v-y-cursive',                  # =, v-y-straight v-y-curly
          'v-eszet-sulzbacher',           # ?
          'v-lambda-straight',            # ?
          'v-zero-slashed',               # =
          'v-one-nobase',                 # = v-one-base
          'v-three-flattop',              # = v-three-twoarcs
          'v-seven-serifed',              # !
          'v-nine-turned-six',            # !
          'v-tilde-high',                 # = v-tilde-low
          'v-asterisk-hexhigh',           # = v-asterisk-hexlow
          'v-underscore-high',            # = v-underscore-low
          'v-paragraph-high',             # ?
          'v-caret-high',                 # = v-caret-low
          'v-brace-straight',             # v-brace-curly
          'v-numbersign-slanted',         # ! v-numbersign-upright
          'v-at-short',                   # ! v-at-threefold
          'v-dollar-open',                # = v-dollar-opencap
          'v-percent-dots',               # = v-percent-rings
          'v-lig-ltgteq-flat',            # ?
          'v-capital-i-serifed',          # v-capital-i-straight
          'v-capital-j-serifed',          # v-capital-j-straight
#       v-f-narrow
#       v-t-narrow
#       v-j-narrow
#       v-r-narrow
       ]

[buildPlans.iosevka-clam.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-clam.weights.bold]
shape = 700
menu  = 700
css   = 700
# End weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-clam.slants]
upright = "normal"
italic = "italic"
# End slant section

[buildPlans.iosevka-clam.widths.normal]
shape = 8          # Width of glyph shapes.
menu  = 8          # Width for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

################################################################################
[buildPlans.iofur]       # <iofur> is your plan name
family = "iofur"         # Font menu family name
design = ['sp-fixed',
          'v-turn-v-straight',     # =
          'v-capital-g-toothless', # =
          'v-capital-q-straight',  # =
          'v-capital-r-straight',  # =
          'v-capital-y-straight',  # =
          'v-a-doublestorey',      # = v-a-singlestorey
          'v-f-straight',          # = v-f-tailed v-f-serifed
          'v-g-opendoublestorey',  # = v-g-doublestorey v-g-singlestorey
          'v-i-zshaped',           # v-i-serifed
          'v-l-italic',            # = v-l-hooky v-l-zshaped
          'v-k-straight',          # ?
          'v-m-normal',            # =, v-m-normal
          'v-r-straight',          # ?, v-r-straight
          'v-t-standard',          # =, v-t-cross
          'v-u-without-bar',       # =, v-u-without-bar
          'v-v-straight',          # ?
          'v-w-straight',          # =, v-w-straight
          'v-x-straight',          # ?
          'v-y-cursive',           # =, v-y-straight v-y-curly
          'v-eszet-sulzbacher',    # ?
          'v-lambda-straight',     # ?
          'v-zero-dotted',         # =
          'v-one-base',            # = v-one-base
          'v-three-flattop',       # = v-three-twoarcs
          'v-seven-noserif',       # !
          'v-nine-turned-six',     # !
          'v-tilde-high',          # = v-tilde-low
          'v-asterisk-hexlow',     # v-asterisk-hexhigh
          'v-underscore-high',     # = v-underscore-low
          'v-paragraph-high',      # ?
          'v-caret-high',          # = v-caret-low
          'v-brace-straight',      # v-brace-curly
          'v-numbersign-upright',  # ! v-numbersign-upright
          'v-at-fourfold',         # ! v-at-threefold
          'v-dollar-through',      # = v-dollar-opencap
          'v-percent-rings',       # = v-percent-rings
          'v-lig-ltgteq-flat',     # ?
          'v-capital-i-serifed',   # v-capital-i-straight
          'v-capital-j-serifed',   # v-capital-j-straight
          'v-f-narrow',
          'v-t-narrow',
          'v-j-narrow',
          'v-r-narrow',
       ]

[buildPlans.iofur.weights.regular]
shape = 350  # Weight for glyph shapes.
menu  = 350  # Weight for the font's names.
css   = 350  # Weight for webfont CSS.

[buildPlans.iofur.weights.bold]
shape = 700  # Weight for glyph shapes.
menu  = 700  # Weight for the font's names.
css   = 700  # Weight for webfont CSS.

# End weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iofur.slants]
upright = "normal"
italic = "italic"
# End slant section

[buildPlans.iofur.widths.normal]
shape = 7          # Width of glyph shapes.
menu  = 7          # Width for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iofur.metric-override]
leading = 1250
winMetricAscenderPad = 0
winMetricDescenderPad = 0
descenderPad = 0   # Additional line height, added to descender.
cap = 735          # Cap height (as well as ascender).
xheight = 200      # X-height.
