[buildPlans.iosevka-clam]       # <iosevka-clam> is your plan name
family = "Iosevka Clam"         # Font menu family name
design = [
  'sp-fixed',
  'v-a-doublestorey',             # singlestorey doublestorey
  'v-ampersand-closed',           # open closed
  'v-asterisk-hexhigh',           # low high hexlow hexhigh
  'v-at-short',                   # short threefold fourfold
  'v-brace-curly',                # curly straight
  'v-capital-g-toothless',        # tooth toothless
  'v-capital-i-serifed',          # straight serifed
  'v-capital-j-serifed',          # straight serifed
  'v-capital-q-straight',         # straight taily
  'v-capital-r-curly',            # straight curly
  'v-capital-y-curly',            # straight curly
  'v-caret-high',                 # low high
  'v-dollar-open',                # open opencap through
  'v-eszet-sulzbacher',           # traditional sulzbacher longs-s-lig
  'v-f-narrow',                   # narrow straight tailed serifed
  'v-f-straight',                 # tailed serifed straight straight-tailed
  'v-g-opendoublestorey',         # opendoublestorey doublestorey singlestorey
  'v-i-italic',                   # serifed hooky zshaped italic
  'v-j-narrow',                   # narrow serifed
  'v-j-serifed',                  # serifed narrow
  'v-k-curly',                    # straight curly cursive
  'v-l-italic',                   # hooky zshaped serifed italic line
                                  # tailed hookybottom
  'v-lambda-straight',            # straight curly
  'v-lig-ltgteq-flat',            # flat slanted
  'v-m-shortleg',                 # shortleg normal
  'v-nine-open-contour',          # open-contour closed-contour
  'v-numbersign-slanted',         # upright slanted
  'v-one-nobase',                 # nobase base
  'v-paragraph-high',             # low high
  'v-percent-dots',               # rings dots
  'v-r-narrow',                   # narrow serifed straight top-serifed
  'v-seven-serifed',              # noserif serifed
  'v-six-open-contour',           # open-contour closed-contour
  'v-t-narrow',                   # narrow cross standard
  'v-t-standard',                 # cross standard
  'v-three-flattop',              # flattop twoarcs
  'v-tilde-high',                 # low high
  'v-turn-v-straight',            # straight curly
  'v-u-with-bar',                 # with-bar without-bar
  'v-underscore-high',            # low high
  'v-v-straight',                 # straight curly
  'v-w-curly',                    # straight curly
  'v-x-curly',                    # straight curly
  'v-y-cursive',                  # straight curly cursive
  'v-zero-slashed',               # slashed dotted unslashed long-dotted
]

[buildPlans.iosevka-clam.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-clam.weights.bold]
shape = 700
menu  = 700
css   = 700
# End weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-clam.slants]
upright = "normal"
italic = "italic"
# End slant section

[buildPlans.iosevka-clam.widths.normal]
shape = 8          # Width of glyph shapes.
menu  = 8          # Width for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.
