[buildPlans.iosevka-clam]        # <iosevka-malc> is your plan name
family = "Iosevka clam"          # Font menu family name

# v-turn-v-straight     # Standard, straight `A`, `Λ`, `Δ`
# v-turn-v-curly        # Slightly curly `A`, `Λ`, `Δ`, like Iosevka 2.x
# v-capital-g-tooth     # Toothed G
# v-capital-g-toothless # Toothless G
# v-capital-q-taily     # `Q` with a curly tail
# v-capital-q-straight  # `Q` with a straight tail like in the old versions
# v-capital-r-straight  # Standard, straight-leg `R`
# v-capital-r-curly     #  Slightly curly-legged `R`, like Iosevka 2.x
# v-capital-y-straight  # Standard, straight `Y`
# v-capital-y-curly     # Slightly curly `Y`, like Iosevka 2.x
# v-a-singlestorey      # Single-storey `a`
# v-a-doublestorey      # Double-storey `a`
# v-f-straight          # `f` without bottom hook
# v-f-tailed            # `f` with a leftward bottom hook
# v-f-serifed           # `f` with bottom serif
# v-g-singlestorey      # Single-storey `g`
# v-g-doublestorey      # Double-storey `g`
# v-g-opendoublestorey  # Open Double-storey `g`, like Trebuchet MS or Fira Code
# v-i-serifed           # Serifed `i`
# v-i-italic            # Italic `i`
# v-i-hooky             # Hooky `i`
# v-i-line              # `i` like a straight line
# v-i-zshaped           # Z-shaped `i`
# v-i-tailed            # Tailed `i`
# v-j-line              # `j` like a straight line
# v-j-serifed           # `j` with top serif
# v-l-hooky             # Hooky `l`
# v-l-zshaped           # Z-shaped `i`
# v-l-serifed           # Serifed `l`
# v-l-italic            # Italic, cursive `l`
# v-l-line              # `l` like a straight line
# v-l-tailed            # `l` with a curved tail
# v-l-hookybottom       # `l` with a straight tail
# v-k-straight          # `k` with standard shape
# v-k-curly             # Slightly curly `k`, like Iosevka 2.x
# v-k-cursive           # `k` with a cursive loop
# v-m-normal            # `m` with normal middle leg, touching the baseline
# v-m-shortleg          # `m` with shorter middle leg, like Ubuntu Mono
# v-r-straight          # Straight, serif-less `r`
# v-r-serifed           # `r` with serif at both top and bottom
# v-r-top-serifed       # `r` with serifs at top-left only
# v-t-standard          # Standard `t` shape
# v-t-cross             # Futura-like `t` shape
# v-u-with-bar          # Normal `u` with right bar
# v-u-without-bar       # Normal `u` without right bar, like a smaller uppercase `U`
# v-v-straight          # Standard, straight `V` and `v`
# v-v-curly             # Slightly curly `V` and `v`, like Iosevka 2.x
# v-w-straight          # Standard, straight `W` and `w`
# v-w-curly             # Slightly curly `W` and `w`, like Iosevka 2.x
# v-x-straight          # Standard, straight `X` and `x`
# v-x-curly             # Slightly curly `X` and `x`, like Iosevka 2.x
# v-y-straight          # More-straight letter `y`
# v-y-curly             # More curly letter `y`, like Iosevka 2.x
# v-y-cursive           # Cursive-like `y`
# v-eszet-traditional   # Fraktur-like Eszet
# v-eszet-sulzbacher    # A more modern, beta-like Eszet
# v-lambda-straight     # More-straight letter `λ`
# v-lambda-curly        # More curly letter `λ`, like Iosevka 2.x
# v-zero-slashed        # Slashed Zero `0`
# v-zero-dotted         # Dotted Zero `0`
# v-zero-unslashed      # O-like `0`
# v-zero-reverse-slashed # Reverse-slashed `0`
# v-one-nobase           # `1` with bottom serif
# v-one-base             # `1` without bottom serif
# v-three-flattop        # Flat top `3` (Like Museo Sans / Montserrat)
# v-three-twoarcs        # Arched top `3`
# v-seven-noserif        # `7` without serif
# v-seven-serifed        # `7` with initial serif
# v-nine-closed-contour  # `9` with a more closed
# v-nine-turned-six      # `9` with a more open contour like a turned `6`
# v-tilde-high           # Higher tilde `~`
# v-tilde-low            # Lower tilde `~`
# v-asterisk-high        # Higher five-pointed asterisk `*`
# v-asterisk-low         # Lower five-pointed asterisk `*`
# v-asterisk-hexhigh     # Higher six-pointed asterisk `*`
# v-asterisk-hexlow      # Lower six-pointed asterisk `*`
# v-underscore-high      # Higher underscore `_`, at baseline
# v-underscore-low       # Lower underscore `_`, below baseline
# v-paragraph-high       # Higher paragraph symbol `¶`
# v-paragraph-low        # Lower paragraph symbol `¶`
# v-caret-high           # Higher circumflex `^`
# v-caret-low            # Lower circumflex `^`
# v-brace-straight       # More straight braces
# v-brace-curly          # More curly braces
# v-numbersign-upright   # Number sign with vertical bars
# v-numbersign-slanted   # Number sign with slanted bars
# v-at-threefold         # The long, three-fold At symbol (`@`)
# v-at-fourfold          # The traditional, four-fold At symbol (`@`)
# v-at-short             # The shorter, Fira-like At symbol (`@`)
# v-dollar-open          # Dollar symbol with open contour
# v-dollar-through       # Dollar symbol with strike-through vertical bar
# v-dollar-opencap       # Dollar symbol with open contour, not exceeding baseline and ascender
# v-dollar-throughcap    # Dollar symbol with strike-through vertical bar, not exceeding baseline and ascender
# v-percent-dots         # Percent `%`, Per-mille `‰` and basis point `‱` using rectangular dots
# v-percent-rings        # Percent `%`, Per-mille `‰` and basis point `‱` using rings
# v-lig-ltgteq-flat      # The lower bar of `<=` and `>=` ligation is flat
# v-lig-ltgteq-slanted   # The lower bar of `<=` and `>=` ligation is slanted

# v-capital-i-straight            # set on purpose to use II diversity
# v-capital-i-serifed
# v-capital-j-straight
# v-capital-j-serifed
# v-f-narrow
# v-t-narrow
# v-j-narrow
# v-j-narrow-serifed
# v-r-narrow

design = ['sp-fixed',
       'v-turn-v-curly',
       'v-capital-g-toothless',
       'v-capital-q-straight',
       'v-capital-r-straight',
       'v-capital-y-straight',
       'v-a-doublestorey',
       'v-f-straight',
       'v-g-opendoublestorey',
       'v-i-hooky',
       'v-j-line',
       'v-l-italic',
       'v-k-curly',
       'v-m-shortleg',
       'v-r-straight',
       'v-t-standard',
       'v-u-with-bar',
       'v-v-straight',
       'v-w-straight',
       'v-x-straight',
       'v-y-curly',
       'v-eszet-traditional',
       'v-lambda-straight',
       'v-zero-slashed',
       'v-one-base',
       'v-three-flattop',
       'v-seven-noserif',
       'v-nine-turned-six',
       'v-tilde-high',
       'v-asterisk-hexhigh',
       'v-underscore-high',
       'v-paragraph-high',
       'v-caret-high',
       'v-brace-curly',
       'v-numbersign-slanted',
       'v-at-threefold',
       'v-dollar-open',
       'v-percent-dots',
       'v-capital-i-serifed',
       'v-capital-j-straight',
       'v-f-narrow',
       'v-t-narrow',
       'v-j-narrow',
       'v-r-narrow'
         ]

# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
[buildPlans.iosevka-clam.weights.regular]
shape = 400                            # Weight for glyph shapes
menu = 400
css = 400

[buildPlans.iosevka-clam.weights.bold]
shape = 700                            # Weight for glyph shapes
menu = 700
css = 700

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-clam.slants]
upright = "normal"
italic = "italic"
