[buildPlans.iosevka-clam]       # <iosevka-clam> is your plan name
family = "Iosevka Clam"         # Font menu family name
design = [
  'sp-fixed',
# single storey a is too much like o
  'v-a-doublestorey',             # singlestorey doublestorey
  'v-ampersand-open',             # open closed
  'v-asterisk-high',              # low high hexlow hexhigh
  'v-at-short',                   # short threefold fourfold
# srtaight { is too much like (
  'v-brace-curly',                # curly straight
  'v-capital-g-toothless',        # tooth toothless
# straight I so too much like |
  'v-capital-i-serifed',          # straight serifed
# straight version of capital J looks too "bland"
  'v-capital-j-serifed',          # straight serifed
  'v-capital-q-straight',         # straight taily
  'v-capital-r-straight',         # straight curly
# straight is out of place in `-y-` for instance
  'v-capital-y-curly',            # straight curly
  'v-caret-high',                 # low high
  'v-dollar-open',                # open opencap through
  'v-eszet-sulzbacher',           # traditional sulzbacher longs-s-lig
  'v-f-straight',                 # narrow tailed serifed straight straight-tail
  'v-g-singlestorey',             # opendoublestorey doublestorey singlestorey
  'v-i-serifed',                  # serifed hooky zshaped italic
  'v-j-serifed',                  # serifed narrow
  'v-k-straight',                 # straight curly cursive
# straight l  - too much like 1
# hooky       - too
# zshaped     - Il combo
# serifed     - too easy to take for 1 with base
# tailed      - `callable`
# hookybottom - too much like italic i
  'v-l-italic',                   # hooky zshaped serifed italic line
                                  # tailed hookybottom
  'v-lambda-straight',            # straight curly
  'v-lig-ltgteq-flat',            # flat slanted
  'v-m-shortleg',                 # shortleg normal
  'v-nine-open-contour',          # open-contour closed-contour
  'v-numbersign-upright',         # upright slanted
# nobase when alone is can be taken for an l
  'v-one-base',                   # nobase base
  'v-paragraph-high',             # low high
  'v-percent-dots',               # rings dots
  'v-r-narrow',                   # narrow serifed straight top-serifed
  'v-seven-noserif',              # noserif serifed
  'v-six-open-contour',           # open-contour closed-contour
  'v-t-narrow',                   # narrow cross standard
  'v-three-flattop',              # flattop twoarcs
  'v-tilde-high',                 # low high
  'v-turn-v-straight',            # straight curly
  'v-u-without-bar',              # with-bar without-bar
  'v-underscore-low',             # low high
  'v-v-straight',                 # straight curly
# v-w- covers both upper and lower case versions and straight captial is hmmm..
  'v-w-curly',                    # straight curly
  'v-x-straight',                 # straight curly
# straight feels out of place
  'v-y-cursive',                  # straight curly cursive
  'v-zero-dotted',                # slashed dotted unslashed
                                  # long-dotted reverse-slashed
]

[buildPlans.iosevka-clam.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-clam.weights.bold]
shape = 700
menu  = 700
css   = 700
# End weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-clam.slants]
upright = "normal"
italic = "italic"
# End slant section

[buildPlans.iosevka-clam.widths.normal]
shape = 8          # Width of glyph shapes.
menu  = 8          # Width for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

# Local Variables:
# compile-command: "sh build.sh"
# End:
